---
- name: download vagrant rpm
  get_url: >-
    url={{vagrant_rpm_url}}
    dest=/tmp/{{vagrant_rpm}}
    owner=root
    group=root
    mode=0644

- name: install vagrant rpm
  package: name='/tmp/{{vagrant_rpm}}' state=present

- name: (Fedora/RedHat) install vagrant-libvirt dependencies
  package: name={{item}} state=present
  with_items:
    - libxslt-devel
    - libxml2-devel
    - libvirt-devel
    - libguestfs-tools-c
  
- name: (Fedora,RedHat) link exportfs into /usr/bin for vagrant
  file: >
    src=/usr/sbin/exportfs
    dest=/usr/bin/exportfs
    state=link
    owner=root
    group=root
    

